// <auto-generated />
using System;
using BookInfoFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookInfoFinder.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20251104064000_AddCategoryNameColumn")]
    partial class AddCategoryNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            
            // Minimal model builder - chỉ cần để migration hoạt động
            modelBuilder.Entity("BookInfoFinder.Models.Entity.SearchHistory", b =>
            {
                b.Property<int>("SearchHistoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                    
                b.Property<string>("CategoryName")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");
                    
                b.HasKey("SearchHistoryId");
                b.ToTable("SearchHistories");
            });
        }
    }
}